import type { MetadataRoute } from "next";

/**
 * F3/F5: PWA manifest. Icons generated by the F5 icon set
 * (public/icons/*). 512px entry is maskable with center safe-zone.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "VonssyAI — BYOK Multi-Model Chat",
    short_name: "VonssyAI",
    description:
      "Bring your own keys. Chat with multiple OpenAI-compatible models through one unified interface.",
    start_url: "/",
    display: "standalone",
    background_color: "#1A1918",
    theme_color: "#FAF9F6",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
